# Generated by Django 2.2.1 on 2019-05-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_avito', models.CharField(default='unknown', max_length=120)),
                ('title', models.CharField(default='unknown', max_length=120)),
                ('price', models.CharField(default='unknown', max_length=120)),
                ('address', models.CharField(default='unknown', max_length=120)),
                ('url', models.CharField(default='unknown', max_length=120)),
                ('tel', models.CharField(default='unknown', max_length=120)),
                ('date_avito', models.CharField(default='unknown', max_length=120)),
            ],
        ),
    ]
